; Add your API keys under the relevant sections
; Example: 

; OpenAI
openai = ""

; Chaos
virustotal = ""

; Shodan
shodan = ""

; Github
spyse = ""

; Facebook
securitytrails = ""

; PassiveTotal
censys = ""

; Twitter
apikey = ""
secret = ""
